#!/bin/bash

# this is a convenience script that creates a simple backup of a remote path

# PARAMETERS
#   1: rclone remote path
#   2: restic repository path

SCRIPT_DIR="$(dirname "$(realpath "$0")")"

if (($# != 2)); then echo "ERROR: Expected 2 positional arguments, but $# where given"; exit 1; fi

"$SCRIPT_DIR"/serve-rclone-mount "$1" restic -r "$2" backup "."
